/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: TuszPro (https://sketchfab.com/TuszPro)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/butter-robot-rick-and-morty-8a9417bd3ce14e71a2945ddbda7e7ecc
title: Butter robot Rick And Morty
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function RickMorty(props) {
  const { nodes, materials } = useGLTF('/rnm.gltf')
  return (
    <group {...props} dispose={null} scale={1.5}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.robot_idmap_0.geometry} material={materials.idmap} />
            <mesh geometry={nodes.robot_lente_0.geometry} material={materials.lente} />
          </group>
        </group>
      </group>
    </group>
  )
}

