const showcaseItems = [
  { id: 1, 
    url: "https://novafusion.my/development/PWA-test/",
    image: require("../assets/images/showcase-smart-axiata.png"),
    item: "Smart Axiata PWA",
    chips: [
      { id: 1, item: "UI" },
      { id: 2, item: "UX" },
      { id: 3, item: "Adobe Illustrator" },
      { id: 4, item: "Adobe Photoshop" },
      { id: 5, item: "Adobe XD" },
      { id: 6, item: "HTML5" },
      { id: 7, item: "CSS" },
      { id: 8, item: "JS" },
      { id: 9, item: "UIKIT" },
      { id: 10, item: "SASS" },
      { id: 11, item: "GSAP" },
      { id: 12, item: "Node" },
      { id: 13, item: "PWA" },
    ],
    type: [
      { id: 1, item: "Web Design" },
      { id: 2, item: "Web Application" },
      { id: 3, item: "Progressive Web Application (PWA)" },
    ],
    desc: "Cambodia’s leading telecommunications operator, offering the fastest 4.5G data speeds, the latest devices and affordable mobile plans.",
    year: "2022"
  },
  { id: 2, 
    url: "https://novafusion.my/snapsite/kpj/",
    image: require("../assets/images/showcase-kpj.png"),
    item: "KPJ Healthcare",
    chips: [
      { id: 1, item: "UI" },
      { id: 2, item: "UX" },
      { id: 3, item: "Adobe Illustrator" },
      { id: 4, item: "Adobe Photoshop" },
      { id: 5, item: "Adobe XD" },
      { id: 6, item: "HTML5" },
      { id: 7, item: "CSS" },
      { id: 8, item: "JS" },
      { id: 9, item: "UIKIT" },
      { id: 10, item: "SASS" },
    ],
    type: [
      { id: 1, item: "Web Design" },
      { id: 2, item: "Web Application" },
    ],
    desc: "KPJ Healthcare Berhad. Delivering What Matters to You. Integrated Annual Report 2021 and Sustainability Report 2021.",
    year: "2022"
  },
];
export default showcaseItems;